### ISSUE TITLE
Tests crash in BaseTestFlowCollector initiallization

### ISSUE THREAD

**Issue by Lamorak** [ologe/flow-test-observer#5]
Simple test

    @Test
    fun flow() = runBlockingTest {
        flowOf(1,2,3).test(this) {
            assertValueCount(3)
        }
    }

Stack trace

    java.lang.AbstractMethodError: kotlinx.coroutines.test.TestCoroutineDispatcher.invokeOnTimeout(JLjava/lang/Runnable;)Lkotlinx/coroutines/DisposableHandle;

	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:75)
	at kotlinx.coroutines.TimeoutKt.access$setupTimeout(Timeout.kt:1)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:31)
	at dev.olog.flow.test.observer.BaseTestFlowCollector.initialize(BaseTestFlowCollector.kt:36)
	at dev.olog.flow.test.observer.BaseTestFlowCollector.setup(BaseTestFlowCollector.kt:25)
	at dev.olog.flow.test.observer.BaseTestFlowCollector.flowValues(BaseTestFlowCollector.kt:53)
	at dev.olog.flow.test.observer.FlowTestCollectorImpl.assertValueCount(FlowTestCollectorImpl.kt:164)

**Comment by ologe** [comment]
HI @Lamorak, that's weird!

Can you share a sample project or your gradle setup?

**Comment by Lamorak** [comment]
Okay, I started a new project with minimal gradle setup and found out that the problem is caused by `androidx.lifecycle`  ktx dependecies

    dependencies {
        def lifecycle_version = "2.2.0"
    
        implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
        implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    
        testImplementation "junit:junit:4.13.1"
        testImplementation "com.github.ologe:flow-test-observer:1.5.0"
        testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.1"
    }

Works fine if I don't use the ktx version

**Comment by ologe** [comment]
After some quick tests, I can't explain why but I found out that you need to add the coroutine dependency to prod

`implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.1"`

**Comment by Lamorak** [comment]
Thank, that solves it 👍
